### ISSUE TITLE
Release a 2.0 with Faraday 2.0 support

### ISSUE THREAD

**Issue by olleolleolle** [lostisland/faraday-rack#2]
Least effort:

- release main as-is

Bonus steps (unrelated)

- [x] move development deps into a Gemfile

**Comment by ismasan** [comment]
Hi, thank you so much for your work!

Any news on when you plan to release this for Faraday 2.0 support?

Best

**Comment by iMacTia** [comment]
I've just released [v2.0.0](https://rubygems.org/gems/faraday-rack/versions/2.0.0) which support Faraday 2.0
